export const ADD_T0_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const INCREASE_ITEM_IN_CART = "INCREASE_ITEM_IN_CART"
export const DECREASE_ITEM_IN_CART = "DECREASE_ITEM_IN_CART"