export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILS = "GET_PRODUCTS_FAILS"

export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS"
export const GET_PRODUCT_DETAIL_FAILS = "GET_PRODUCTS_DETAIL_FAILS"

export const REVIEW = "REVIEW"